# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

image: amdenterpriseai/aim-mistralai-mixtral-8x7b-instruct-v0-1:0.8.4
model: mistralai/Mixtral-8x7B-Instruct-v0.1
gpus: 1

