# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

image: amdenterpriseai/aim-qwen-qwen3-vl-235b-a22b-thinking:0.11.0
model: Qwen/Qwen3-VL-235B-A22B-Thinking
gpus: 2
