# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

image: amdenterpriseai/aim-google-gemma-3-27b-it:0.11.0
model: google/gemma-3-27b-it
gpus: 1

env_vars:
  HF_TOKEN:
    key: hf-token
    name: hf-token
