# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

image: amdenterpriseai/aim-zai-org-glm-4-7:0.12.0
model: zai-org/GLM-4.7
gpus: 2

env_vars:
  HF_TOKEN:
    key: hf-token
    name: hf-token
