# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

image: amdenterpriseai/aim-mistralai-mistral-large-3-675b-instruct-2512:0.10.0
model: mistralai/Mistral-Large-3-675B-Instruct-2512
gpus: 8

