# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

image: amdenterpriseai/aim-mistralai-ministral-3-14b-instruct-2512:0.10.0
model: mistralai/Ministral-3-14B-Instruct-2512
gpus: 1

