# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

image: amdenterpriseai/aim-coherelabs-command-a-reasoning-08-2025:0.9.0
model: CohereLabs/command-a-reasoning-08-2025
gpus: 2

env_vars:
  HF_TOKEN:
    key: hf-token
    name: hf-token
