apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kgateway-collector.yaml
- traces-collector-static.yaml
- http-listener-tracing-policy.yaml
- tracing-reference-grant.yaml
- vllm-sidecar-collector.yaml

commonLabels:
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: kgateway-observability
